CC=i386-elf-gcc 
all:
	$(CC) -c cmp.c -o cmp.o -nostdlib -ffreestanding -I../include 
	$(CC) -c cpy.c -o cpy.o -nostdlib -ffreestanding -I../include -std=gnu99
	$(CC) -c strlen.c -o strlen.o -nostdlib -ffreestanding -I../include
